version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run Application Test
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --logger "trx" --results-directory "TestResults" --collect:"Code Coverage"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults/*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults

  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Release"
          command: dotnet.exe build --configuration Release --output bin/Release/
      - store_artifacts:
          path: bin/Release/
          destination: bin/Release/

  package:
    description: Package and publish the application with Release configuration
    executor:
      name: windows/default
    steps:
      - run:
          name: "print env var"
          command: echo $CIRCLE_PROJECT_REPONAME
      - run:
         name: "Pack"
         command: dotnet pack --configuration Release
      - run:
         name: "Publish"
         command: dotnet nuget push "bin/Release/$CIRCLE_PROJECT_REPONAME.*.nupkg" --source "github"
      - store_artifacts:
         path: bin/Release/$CIRCLE_PROJECT_REPONAME.*.nupkg
         destination: nupkgs/

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
      - package:
           requires:
            - build