version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run Application Test
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --logger "trx" --results-directory "TestResults" --collect:"Code Coverage"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults/*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults

  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Release"
          command: dotnet.exe build --configuration Release --output bin/Release/

  package:
    description: Package and publish the application with Release configuration
    executor:
      name: windows/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dd:3a:37:de:f8:ab:a5:91:58:df:bd:bb:05:1d:15:3a"
      - checkout
      - run:
         name: "Pack"
         command: dotnet pack --configuration Release --output nupkgs/
      - run:
         name: "Create rename the nuget.config file to be use as a source"
         command: mv nugetconfig nuget.config
      - run:
        name: "sed to put the github token into the file safely"
        comman: sed -i 's/GITHUB_TOKEN/$GITHUB_TOKEN/g'
      - run:
         name: "Publish"
         command: dotnet nuget push nupkgs/xor.csharp.extensions.fluent.1.0.0.nupkg --source "github"
      - store_artifacts:
         path: nupkgs/
         destination: nupkgs/

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
      - package:
           requires:
            - build
