version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build --logger "trx"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
      - store_artifacts:
          path: tests/TestResults
          destination: TestResults

  build:
    description: Build Application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Release"
          command: dotnet.exe build --configuration Release

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
