version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run Application Test
    executor:
      name: windows/default
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --logger "trx" --results-directory "TestResults" --collect:"Code Coverage"
      - run:
          name: test results
          when: always
          command: |
            dotnet tool install -g trx2junit
            trx2junit TestResults/*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults

  build:
    description: Build and Package application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Release"
          command: dotnet.exe build --configuration Release --output bin/Release/
      - run:
          name: "Pack"
          command: dotnet pack --configuration Release --output nupkgs/
      - run:
          name: "FUCK"
          command: echo $env:GITHUB_TOKEN
      - run:
          name: "Create the nuget.config file to be use as a source"
          command: (Get-Content nugetconfig).replace('GITHUB_TOKEN', $env:GITHUB_TOKEN) | Set-Content nuget.config
      - run:
          name: "DEBUG nuget.config"
          command: cat nuget.config
      - run:
          name: "Publish"
          command: dotnet nuget push nupkgs/xor.csharp.extensions.fluent.1.0.0.nupkg --source "github"
      - store_artifacts:
          path: nupkgs/
          destination: nupkgs/

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
